server:
  port: 8787

spring:
  application:
    name: clean-architecture-proposal
  datasource:
    url: jdbc:postgresql://localhost:5432/clean-architecture-proposal
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        show_sql: false
    generate-ddl: true